//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class actividades
{
    public long id { get; set; }
    public Nullable<long> id_reclamo { get; set; }
    public Nullable<int> id_tipo { get; set; }
    public Nullable<int> id_movimiento { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string usuario { get; set; }

    public virtual movimientos movimientos { get; set; }
    public virtual tipo_reclamos tipo_reclamos { get; set; }
}

public partial class ajustadores
{
    public int id { get; set; }
    public string nombre { get; set; }
    public string aseguradora { get; set; }
    public string telefono { get; set; }
    public string correo { get; set; }
    public string estado { get; set; }
    public Nullable<int> id_usuario { get; set; }
    public Nullable<short> id_cabina { get; set; }
    public string tipo { get; set; }
}

public partial class analistas
{
    public analistas()
    {
        this.reclamo_auto = new HashSet<reclamo_auto>();
        this.reclamos_varios = new HashSet<reclamos_varios>();
    }

    public int id { get; set; }
    public string nombre { get; set; }
    public string Empresa { get; set; }
    public string telefono { get; set; }
    public string correo { get; set; }
    public Nullable<bool> estado { get; set; }
    public string tipo { get; set; }

    public virtual ICollection<reclamo_auto> reclamo_auto { get; set; }
    public virtual ICollection<reclamos_varios> reclamos_varios { get; set; }
}

public partial class archivos_copagos
{
    public int id { get; set; }
    public Nullable<System.DateTime> fechareg { get; set; }
    public string usuario { get; set; }
    public string path { get; set; }
    public string nombre { get; set; }
    public string nombre_archivo { get; set; }
}

public partial class aseguradoras
{
    public aseguradoras()
    {
        this.carpetas_aseguradoras = new HashSet<carpetas_aseguradoras>();
    }

    public int id { get; set; }
    public string aseguradora { get; set; }
    public Nullable<short> codigo { get; set; }
    public Nullable<short> total_dias_rc_medicos { get; set; }

    public virtual ICollection<carpetas_aseguradoras> carpetas_aseguradoras { get; set; }
}

public partial class asegurados_caja_ahorro
{
    public int id { get; set; }
    public string poliza { get; set; }
    public string nombre { get; set; }
    public string modelo { get; set; }
    public string marca { get; set; }
    public string linea { get; set; }
    public string placa { get; set; }
    public string empresa { get; set; }
}

public partial class asegurados_consultas
{
    public int id { get; set; }
    public string poliza { get; set; }
    public string placa { get; set; }
    public string nombre { get; set; }
    public string modelo { get; set; }
    public string marca { get; set; }
    public string linea { get; set; }
    public string chasis { get; set; }
    public string fecha_registro { get; set; }
    public string estado { get; set; }
}

public partial class asegurados_implants
{
    public int id { get; set; }
    public string asegurado { get; set; }
    public string telefono { get; set; }
    public string correo { get; set; }
    public string empresa { get; set; }
    public string motivo { get; set; }
    public string comentario { get; set; }
    public string usuario { get; set; }
    public Nullable<System.DateTime> fechareg { get; set; }
    public Nullable<System.DateTime> fechafin { get; set; }
    public Nullable<bool> estado { get; set; }
}

public partial class auto_reclamo
{
    public auto_reclamo()
    {
        this.reclamo_auto = new HashSet<reclamo_auto>();
    }

    public long id { get; set; }
    public string placa { get; set; }
    public string color { get; set; }
    public string modelo { get; set; }
    public string chasis { get; set; }
    public string motor { get; set; }
    public string propietario { get; set; }
    public string marca { get; set; }
    public string poliza { get; set; }
    public string ejecutivo { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public string estado_poliza { get; set; }
    public string asegurado { get; set; }
    public string vip { get; set; }
    public string inciso { get; set; }
    public string moneda { get; set; }
    public string direccion { get; set; }
    public Nullable<System.DateTime> vigencia_inicial { get; set; }
    public Nullable<System.DateTime> vigencia_final { get; set; }
    public Nullable<short> cia { get; set; }
    public Nullable<short> secren { get; set; }
    public Nullable<short> numero_gestor { get; set; }
    public Nullable<short> numRamo { get; set; }
    public Nullable<int> cliente { get; set; }
    public string programa { get; set; }
    public string vendedor { get; set; }

    public virtual ICollection<reclamo_auto> reclamo_auto { get; set; }
}

public partial class autorizaciones
{
    public autorizaciones()
    {
        this.bitacora_autorizaciones = new HashSet<bitacora_autorizaciones>();
    }

    public long id { get; set; }
    public string reportante { get; set; }
    public string tipo_consulta { get; set; }
    public string tipo_estado { get; set; }
    public string correo { get; set; }
    public string telefono { get; set; }
    public string metodo { get; set; }
    public System.TimeSpan hora_commit { get; set; }
    public System.DateTime fecha_commit { get; set; }
    public int id_usuario { get; set; }
    public int id_cabina { get; set; }
    public long id_reg_reclamos_medicos { get; set; }
    public Nullable<short> codigo_pais { get; set; }
    public Nullable<System.DateTime> fecha_cierre { get; set; }
    public Nullable<System.TimeSpan> hora_cierre { get; set; }
    public string tiempo_de_cierre { get; set; }
    public Nullable<System.DateTime> fecha_completa_commit { get; set; }
    public Nullable<System.DateTime> fecha_completa_cierre { get; set; }
    public string total_tiempo { get; set; }
    public Nullable<bool> tramite_directo { get; set; }

    public virtual cabina cabina { get; set; }
    public virtual reg_reclamos_medicos reg_reclamos_medicos { get; set; }
    public virtual usuario usuario { get; set; }
    public virtual ICollection<bitacora_autorizaciones> bitacora_autorizaciones { get; set; }
}

public partial class bitacora_autorizaciones
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public string estado { get; set; }
    public Nullable<System.TimeSpan> hora_commit { get; set; }
    public Nullable<System.DateTime> fecha_commit { get; set; }
    public long id_autorizaciones { get; set; }
    public string usuario { get; set; }

    public virtual autorizaciones autorizaciones { get; set; }
}

public partial class bitacora_autos_unity
{
    public int id { get; set; }
    public Nullable<System.DateTime> hora_commit { get; set; }
    public Nullable<System.DateTime> fecha_commit { get; set; }
    public Nullable<long> id_reclamo_auto { get; set; }
    public string status { get; set; }

    public virtual reclamo_auto reclamo_auto { get; set; }
}

public partial class bitacora_consulta_movil
{
    public int id { get; set; }
    public string campo_busqueda { get; set; }
    public string poliza { get; set; }
    public string usuario { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<bool> reviso_coberturas { get; set; }
}

public partial class bitacora_estados_autos
{
    public long id { get; set; }
    public string estado { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<long> id_reclamo_auto { get; set; }

    public virtual reclamo_auto reclamo_auto { get; set; }
}

public partial class bitacora_estados_reclamos_varios
{
    public int id { get; set; }
    public string estado { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<int> id_reclamos_varios { get; set; }

    public virtual reclamos_varios reclamos_varios { get; set; }
}

public partial class bitacora_reclamo_auto
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public Nullable<System.DateTime> fecha_commit { get; set; }
    public Nullable<System.TimeSpan> hora_commit { get; set; }
    public long id_reclamo { get; set; }
    public string usuario { get; set; }

    public virtual reclamo_auto reclamo_auto { get; set; }
}

public partial class bitacora_reclamos_medicos
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public Nullable<System.TimeSpan> hora_commit { get; set; }
    public Nullable<System.DateTime> fecha_commit { get; set; }
    public long id_reclamos_medicos { get; set; }
    public string usuario { get; set; }

    public virtual reclamos_medicos reclamos_medicos { get; set; }
}

public partial class bitacora_reclamos_varios
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public Nullable<System.TimeSpan> hora_commit { get; set; }
    public Nullable<System.DateTime> fecha_commit { get; set; }
    public int id_reclamos_varios { get; set; }
    public string usuario { get; set; }

    public virtual reclamos_varios reclamos_varios { get; set; }
}

public partial class busqCoberturasPolizasDaños
{
    public int id { get; set; }
    public string descr { get; set; }
    public string poliza { get; set; }
    public Nullable<double> sumaaseg { get; set; }
    public Nullable<short> secart { get; set; }
    public Nullable<double> limite1 { get; set; }
    public Nullable<double> limite2 { get; set; }
    public Nullable<double> deducible { get; set; }
    public Nullable<double> prima { get; set; }
}

public partial class cabina
{
    public cabina()
    {
        this.autorizaciones = new HashSet<autorizaciones>();
        this.reclamo_auto = new HashSet<reclamo_auto>();
        this.reclamos_medicos = new HashSet<reclamos_medicos>();
        this.reclamos_varios = new HashSet<reclamos_varios>();
        this.usuario = new HashSet<usuario>();
    }

    public int id { get; set; }
    public string nombre { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public int id_sucursal { get; set; }

    public virtual ICollection<autorizaciones> autorizaciones { get; set; }
    public virtual sucursal sucursal { get; set; }
    public virtual ICollection<reclamo_auto> reclamo_auto { get; set; }
    public virtual ICollection<reclamos_medicos> reclamos_medicos { get; set; }
    public virtual ICollection<reclamos_varios> reclamos_varios { get; set; }
    public virtual ICollection<usuario> usuario { get; set; }
}

public partial class cabina_virtual
{
    public int id { get; set; }
    public string nombre { get; set; }
    public string correo { get; set; }
    public string telefono { get; set; }
    public string codigo { get; set; }
    public Nullable<System.DateTime> fechareg { get; set; }
    public Nullable<System.DateTime> fecha_atencion { get; set; }
    public Nullable<bool> estado { get; set; }
    public string empresa { get; set; }
    public string motivo { get; set; }
}

public partial class carpetas_aseguradoras
{
    public carpetas_aseguradoras()
    {
        this.formularios_aseguradoras = new HashSet<formularios_aseguradoras>();
    }

    public int id { get; set; }
    public Nullable<int> id_aseguradora { get; set; }
    public string nombre_carpeta { get; set; }

    public virtual aseguradoras aseguradoras { get; set; }
    public virtual ICollection<formularios_aseguradoras> formularios_aseguradoras { get; set; }
}

public partial class cartas
{
    public int id { get; set; }
    public string contenido { get; set; }
    public string tipo { get; set; }
    public string modulo { get; set; }
    public Nullable<int> id_reclamo { get; set; }
}

public partial class clientes
{
    public int id { get; set; }
    public string codigo { get; set; }
    public string nombre { get; set; }
    public string correo { get; set; }
    public string telefono { get; set; }
    public Nullable<System.DateTime> fechareg { get; set; }
}

public partial class coberturas
{
    public int id { get; set; }
    public string cobertura { get; set; }
    public string tipo { get; set; }
}

public partial class coberturas_afectadas
{
    public int id { get; set; }
    public string cobertura { get; set; }
    public Nullable<long> id_reclamo_auto { get; set; }
    public Nullable<decimal> limite1 { get; set; }
    public Nullable<decimal> limite2 { get; set; }
    public Nullable<decimal> deducible { get; set; }
    public Nullable<decimal> prima { get; set; }

    public virtual reclamo_auto reclamo_auto { get; set; }
}

public partial class coberturas_afectadas_danios
{
    public int id { get; set; }
    public string cobertura { get; set; }
    public Nullable<decimal> limite1 { get; set; }
    public Nullable<decimal> limite2 { get; set; }
    public Nullable<decimal> deducible { get; set; }
    public Nullable<decimal> prima { get; set; }
    public Nullable<int> id_reclamos_varios { get; set; }

    public virtual reclamos_varios reclamos_varios { get; set; }
}

public partial class comentarios_reclamos_autos
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public string usuario { get; set; }
    public Nullable<long> id_reclamo_auto { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<System.TimeSpan> hora { get; set; }

    public virtual reclamo_auto reclamo_auto { get; set; }
}

public partial class comentarios_reclamos_medicos
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public string usuario { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string estado { get; set; }
    public Nullable<long> id_reclamo_medico { get; set; }

    public virtual reclamos_medicos reclamos_medicos { get; set; }
}

public partial class comentarios_reclamos_varios
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public string usuario { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<int> id_reclamos_varios { get; set; }

    public virtual reclamos_varios reclamos_varios { get; set; }
}

public partial class consultar_asegurados
{
    public int id { get; set; }
    public string tipo { get; set; }
    public string asegurado { get; set; }
    public string poliza { get; set; }
    public string ramo { get; set; }
    public string placa { get; set; }
    public Nullable<int> cliente { get; set; }
    public Nullable<System.DateTime> vigi { get; set; }
    public Nullable<System.DateTime> vigf { get; set; }
}

public partial class contacto_auto
{
    public int id { get; set; }
    public string contacto { get; set; }
    public string telefono { get; set; }
    public string correo { get; set; }
    public Nullable<long> id_reclamo_auto { get; set; }

    public virtual reclamo_auto reclamo_auto { get; set; }
}

public partial class contactos_reclamos_varios
{
    public int id { get; set; }
    public string nombre { get; set; }
    public string telefono { get; set; }
    public string correo { get; set; }
    public Nullable<int> id_reclamos_varios { get; set; }
}

public partial class descuentos_vifrio
{
    public int id { get; set; }
    public string servicio { get; set; }
    public string descuento { get; set; }
    public string empresa { get; set; }
}

public partial class detalle_gasto_medico
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public Nullable<decimal> cantidad { get; set; }
    public string num_factura { get; set; }
    public string moneda { get; set; }
    public Nullable<System.DateTime> fecha_gasto_medico { get; set; }
    public Nullable<long> id_reclamo_medico { get; set; }

    public virtual reclamos_medicos reclamos_medicos { get; set; }
}

public partial class detalle_pagos_reclamos_autos
{
    public int id { get; set; }
    public string cobertura_pagada { get; set; }
    public Nullable<decimal> monto { get; set; }
    public Nullable<decimal> iva { get; set; }
    public Nullable<decimal> deducible { get; set; }
    public Nullable<decimal> timbres { get; set; }
    public Nullable<decimal> primas { get; set; }
    public Nullable<decimal> total { get; set; }
    public Nullable<long> id_reclamo_auto { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string destino { get; set; }

    public virtual reclamo_auto reclamo_auto { get; set; }
}

public partial class detalle_pagos_reclamos_medicos
{
    public int id { get; set; }
    public Nullable<decimal> total_reclamado { get; set; }
    public Nullable<decimal> total_aprobado { get; set; }
    public Nullable<decimal> total_no_cubierto { get; set; }
    public Nullable<decimal> total_iva { get; set; }
    public Nullable<decimal> deducible { get; set; }
    public Nullable<decimal> coaseguro { get; set; }
    public Nullable<decimal> copago { get; set; }
    public Nullable<decimal> timbres { get; set; }
    public Nullable<decimal> total { get; set; }
    public string no_cheque { get; set; }
    public Nullable<decimal> porcen_coaseguro { get; set; }
    public Nullable<decimal> porcen_timbres { get; set; }
    public string moneda { get; set; }
    public string banco { get; set; }
    public Nullable<decimal> monto { get; set; }
    public string no_transferencia { get; set; }
    public Nullable<decimal> monto_transferencia { get; set; }
    public Nullable<System.DateTime> fecha_transferencia { get; set; }
    public Nullable<System.DateTime> fecha_creacion { get; set; }
    public long id_reclamo_medico { get; set; }

    public virtual reclamos_medicos reclamos_medicos { get; set; }
}

public partial class detalle_pagos_reclamos_varios
{
    public int id { get; set; }
    public string cobertura_pagada { get; set; }
    public string ramo { get; set; }
    public string tipo_pago { get; set; }
    public Nullable<decimal> monto_reclamado { get; set; }
    public Nullable<decimal> monto_ajustado { get; set; }
    public Nullable<decimal> mejora_tecnologica { get; set; }
    public Nullable<decimal> tiempo_uso { get; set; }
    public Nullable<decimal> infra_seguro { get; set; }
    public Nullable<decimal> perdida_final_ajustada { get; set; }
    public Nullable<decimal> iva { get; set; }
    public Nullable<decimal> deducible { get; set; }
    public Nullable<decimal> timbres { get; set; }
    public Nullable<decimal> primas { get; set; }
    public Nullable<decimal> salvamento { get; set; }
    public Nullable<decimal> valor_indemnizado { get; set; }
    public Nullable<int> id_reclamos_varios { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string destino { get; set; }
    public string no_cheque { get; set; }
    public string nombre_emision_cheque { get; set; }
    public string medio_pago { get; set; }

    public virtual reclamos_varios reclamos_varios { get; set; }
}

public partial class direcciones
{
    public int id { get; set; }
    public Nullable<int> cliente { get; set; }
    public string direccion { get; set; }
    public string email { get; set; }
    public int tipo_direccion { get; set; }
}

public partial class direcciones_clientes_gm
{
    public int id { get; set; }
    public Nullable<int> cliente { get; set; }
    public string poliza { get; set; }
    public string direccion { get; set; }
}

public partial class documentos_medicos
{
    public byte id { get; set; }
    public string descripcion { get; set; }
    public string tipo { get; set; }
}

public partial class documentos_solicitados
{
    public int id { get; set; }
    public Nullable<int> documento { get; set; }
    public Nullable<int> id_reclamo { get; set; }
    public string tipo { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }

    public virtual tipo_documentos tipo_documentos { get; set; }
}

public partial class ejecutivos
{
    public int id { get; set; }
    public string gestor { get; set; }
    public Nullable<short> codigo { get; set; }
    public string correo { get; set; }
    public string telefono { get; set; }
}

public partial class empresa
{
    public empresa()
    {
        this.sucursal = new HashSet<sucursal>();
    }

    public int id { get; set; }
    public string nombre { get; set; }
    public int id_pais { get; set; }

    public virtual pais pais { get; set; }
    public virtual ICollection<sucursal> sucursal { get; set; }
}

public partial class empresas_implants
{
    public int id { get; set; }
    public string nombre { get; set; }
    public Nullable<System.DateTime> fechareg { get; set; }
}

public partial class encuesta
{
    public int id { get; set; }
    public string servicio { get; set; }
    public string empresa { get; set; }
    public Nullable<short> pregunta1 { get; set; }
    public string clasificacion1 { get; set; }
    public string comentario1 { get; set; }
    public Nullable<short> pregunta2 { get; set; }
    public string clasificacion2 { get; set; }
    public string comentario2 { get; set; }
    public Nullable<short> pregunta3 { get; set; }
    public string clasificacion3 { get; set; }
    public string comentario3 { get; set; }
    public string comentario { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string telefono { get; set; }
    public string nombre { get; set; }
    public string codigo { get; set; }
    public string correo { get; set; }
    public string gestion { get; set; }
}

public partial class encuesta_egresos
{
    public int id { get; set; }
    public string hospital { get; set; }
    public string asegurado { get; set; }
    public string pregunta1 { get; set; }
    public string pregunta2 { get; set; }
    public string comentarios { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
}

public partial class encuesta_recepcion
{
    public int id { get; set; }
    public string empresa { get; set; }
    public Nullable<short> pregunta1 { get; set; }
    public string clasificacion1 { get; set; }
    public string comentario1 { get; set; }
    public string tipo_servicio { get; set; }
    public Nullable<short> pregunta2 { get; set; }
    public string clasificacion2 { get; set; }
    public string comentario2 { get; set; }
    public Nullable<short> pregunta3 { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
}

public partial class errores_insercion
{
    public int id { get; set; }
    public Nullable<int> numero { get; set; }
    public string descripcion { get; set; }
    public string seccion { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
}

public partial class estado
{
    public estado()
    {
        this.reclamo_auto = new HashSet<reclamo_auto>();
        this.reclamos_medicos = new HashSet<reclamos_medicos>();
        this.reclamos_varios = new HashSet<reclamos_varios>();
    }

    public int id { get; set; }
    public string nombre { get; set; }

    public virtual ICollection<reclamo_auto> reclamo_auto { get; set; }
    public virtual ICollection<reclamos_medicos> reclamos_medicos { get; set; }
    public virtual ICollection<reclamos_varios> reclamos_varios { get; set; }
}

public partial class estados_reclamos_unity
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public Nullable<short> dias_revision { get; set; }
    public string tipo { get; set; }
}

public partial class flotillas
{
    public int id { get; set; }
    public Nullable<int> inciso { get; set; }
    public string propietario { get; set; }
    public string marca { get; set; }
    public string linea { get; set; }
    public string chasis { get; set; }
    public string motor { get; set; }
    public string year { get; set; }
    public string color { get; set; }
    public string placa { get; set; }
    public string usuario { get; set; }
    public string aseguradora { get; set; }
    public string asegurado { get; set; }
    public string poliza { get; set; }
    public string vigencia { get; set; }
    public string ejecutivo { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string estado { get; set; }
    public string usuario_inactivacion { get; set; }
    public string codigo_interno { get; set; }
    public string pagador { get; set; }
}

public partial class formulario_colectivo
{
    public int id { get; set; }
    public string poliza { get; set; }
    public string certificado { get; set; }
    public string vigencia { get; set; }
    public string contratante { get; set; }
    public string nombre_titular { get; set; }
    public string dpi { get; set; }
    public string nit { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public string email { get; set; }
    public string nombre_asegurado_titular { get; set; }
    public string ocupacion_titular { get; set; }
    public string peso_titular { get; set; }
    public string estatura_titular { get; set; }
    public string fecha_nacimiento_titular { get; set; }
    public string nombre_conyuge { get; set; }
    public string ocupacion_conyuge { get; set; }
    public string peso_conyuge { get; set; }
    public string estatura_conyuge { get; set; }
    public string fecha_nacimiento_conyuge { get; set; }
    public string nombre_hijo1 { get; set; }
    public string ocupacion_hijo1 { get; set; }
    public string peso_hijo1 { get; set; }
    public string estatura_hijo1 { get; set; }
    public string fecha_nacimiento_hijo1 { get; set; }
    public string nombre_hijo2 { get; set; }
    public string ocupacion_hijo2 { get; set; }
    public string peso_hijo2 { get; set; }
    public string estatura_hijo2 { get; set; }
    public string fecha_nacimiento_hijo2 { get; set; }
    public string nombre_hijo3 { get; set; }
    public string ocupacion_hijo3 { get; set; }
    public string peso_hijo3 { get; set; }
    public string estatura_hijo3 { get; set; }
    public string fecha_nacimiento_hijo3 { get; set; }
    public string nombre_beneficiario1 { get; set; }
    public string parentesco_ben1 { get; set; }
    public string porcentaje_ben1 { get; set; }
    public string nombre_beneficiario2 { get; set; }
    public string parentesco_ben2 { get; set; }
    public string porcentaje_ben2 { get; set; }
    public Nullable<bool> enfermedades { get; set; }
    public string detalle_enfermedades { get; set; }
    public Nullable<bool> impedimentos { get; set; }
    public string detalle_impedimentos { get; set; }
    public string enfermedades_recientes { get; set; }
    public Nullable<bool> actividad_peligrosa { get; set; }
    public string detalle_actividad_peligrosa { get; set; }
    public string lugar_fecha { get; set; }
    public string solicitante { get; set; }
    public string firma { get; set; }
}

public partial class formularios_aseguradoras
{
    public int id { get; set; }
    public Nullable<int> id_carpeta { get; set; }
    public string ruta { get; set; }
    public string usuario { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }

    public virtual carpetas_aseguradoras carpetas_aseguradoras { get; set; }
}

public partial class gestores
{
    public gestores()
    {
        this.reclamo_auto = new HashSet<reclamo_auto>();
        this.reclamos_varios = new HashSet<reclamos_varios>();
    }

    public short id { get; set; }
    public string nombre { get; set; }
    public string correo { get; set; }
    public string telefono { get; set; }
    public Nullable<bool> estado { get; set; }
    public string usuario { get; set; }
    public string tipo { get; set; }

    public virtual ICollection<reclamo_auto> reclamo_auto { get; set; }
    public virtual ICollection<reclamos_varios> reclamos_varios { get; set; }
}

public partial class info_asegurado
{
    public int id { get; set; }
    public string poliza { get; set; }
    public string ejecutivo { get; set; }
    public string asegurado { get; set; }
    public string parentesco { get; set; }
    public string carne { get; set; }
    public Nullable<bool> estado { get; set; }
}

public partial class ingreso_cheques
{
    public int id { get; set; }
    public Nullable<int> usuario { get; set; }
    public Nullable<long> id_reclamo { get; set; }
    public string tipo { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }

    public virtual reclamos_medicos reclamos_medicos { get; set; }
}

public partial class maternidad
{
    public int id { get; set; }
    public string poliza { get; set; }
    public string asegurado { get; set; }
    public Nullable<int> cod_ejecutivo { get; set; }
    public string ejecutivo { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<System.DateTime> fecha_parto { get; set; }
    public Nullable<bool> estado { get; set; }
}

public partial class motivos_cierre
{
    public motivos_cierre()
    {
        this.reclamo_auto = new HashSet<reclamo_auto>();
    }

    public int id { get; set; }
    public string nombre { get; set; }

    public virtual ICollection<reclamo_auto> reclamo_auto { get; set; }
}

public partial class movimientos
{
    public movimientos()
    {
        this.actividades = new HashSet<actividades>();
    }

    public int id { get; set; }
    public string nombre { get; set; }

    public virtual ICollection<actividades> actividades { get; set; }
}

public partial class pais
{
    public pais()
    {
        this.empresa = new HashSet<empresa>();
    }

    public int id { get; set; }
    public string nombre { get; set; }
    public string moneda { get; set; }
    public string codigo_pais { get; set; }

    public virtual ICollection<empresa> empresa { get; set; }
}

public partial class ramos
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public Nullable<short> ramo { get; set; }
}

public partial class recibos_medicos
{
    public int id { get; set; }
    public string descripcion { get; set; }
    public string comentarios { get; set; }
    public string cantidad { get; set; }
    public Nullable<long> id_reclamo_medico { get; set; }

    public virtual reclamos_medicos reclamos_medicos { get; set; }
}

public partial class reclamo_auto
{
    public reclamo_auto()
    {
        this.bitacora_autos_unity = new HashSet<bitacora_autos_unity>();
        this.bitacora_estados_autos = new HashSet<bitacora_estados_autos>();
        this.bitacora_reclamo_auto = new HashSet<bitacora_reclamo_auto>();
        this.coberturas_afectadas = new HashSet<coberturas_afectadas>();
        this.comentarios_reclamos_autos = new HashSet<comentarios_reclamos_autos>();
        this.contacto_auto = new HashSet<contacto_auto>();
        this.detalle_pagos_reclamos_autos = new HashSet<detalle_pagos_reclamos_autos>();
    }

    public long id { get; set; }
    public string boleta { get; set; }
    public string titular { get; set; }
    public string ubicacion { get; set; }
    public Nullable<System.TimeSpan> hora { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string reportante { get; set; }
    public string piloto { get; set; }
    public Nullable<short> edad { get; set; }
    public string telefono { get; set; }
    public string ajustador { get; set; }
    public string version { get; set; }
    public string metodo { get; set; }
    public string num_reclamo { get; set; }
    public long id_auto_reclamo { get; set; }
    public int id_estado { get; set; }
    public int id_cabina { get; set; }
    public int id_usuario { get; set; }
    public Nullable<short> codigo_pais { get; set; }
    public Nullable<System.TimeSpan> hora_commit { get; set; }
    public Nullable<System.DateTime> fecha_commit { get; set; }
    public string estado_unity { get; set; }
    public string usuario_unity { get; set; }
    public Nullable<System.DateTime> fecha_cierre { get; set; }
    public Nullable<System.TimeSpan> hora_cierre { get; set; }
    public string tipo_servicio { get; set; }
    public Nullable<short> id_gestor { get; set; }
    public Nullable<int> id_analista { get; set; }
    public Nullable<int> id_taller { get; set; }
    public Nullable<int> id_motivo_cierre { get; set; }
    public string observaciones { get; set; }
    public string estado_auto_unity { get; set; }
    public Nullable<bool> complicado { get; set; }
    public Nullable<bool> prioritario { get; set; }
    public Nullable<bool> compromiso_pago { get; set; }
    public Nullable<bool> perdida_total { get; set; }
    public Nullable<bool> robo { get; set; }
    public Nullable<bool> alquiler_auto { get; set; }
    public Nullable<bool> cierre_interno { get; set; }
    public Nullable<System.DateTime> fecha_visualizar { get; set; }
    public string asignado_por { get; set; }
    public Nullable<System.DateTime> fecha_asignacion { get; set; }
    public Nullable<System.DateTime> fecha_apertura_reclamo { get; set; }
    public Nullable<System.DateTime> fecha_cierre_reclamo { get; set; }
    public Nullable<bool> acs { get; set; }
    public string detalle_no_conforme { get; set; }
    public Nullable<bool> no_conforme { get; set; }
    public Nullable<System.DateTime> fecha_no_conforme { get; set; }
    public Nullable<System.DateTime> fecha_cierre_no_conforme { get; set; }
    public string observacion_no_conforme { get; set; }
    public Nullable<bool> b_carta_cierre_interno { get; set; }
    public Nullable<bool> b_carta_declinado { get; set; }
    public Nullable<bool> b_carta_envio_cheque { get; set; }
    public Nullable<bool> b_carta_alerta_tiempo { get; set; }
    public string documentos { get; set; }
    public Nullable<bool> problema_taller { get; set; }
    public Nullable<bool> problema_cabina { get; set; }
    public Nullable<bool> problema_ajustador { get; set; }
    public Nullable<bool> problema_ejecutivo { get; set; }
    public Nullable<bool> problema_aseguradora { get; set; }
    public string comentario_taller { get; set; }
    public string comentario_ajustador { get; set; }
    public string comentario_cabina { get; set; }
    public string comentario_ejecutivo { get; set; }
    public string comentario_aseguradora { get; set; }
    public Nullable<System.DateTime> fecha_problema { get; set; }
    public Nullable<bool> importacion { get; set; }
    public Nullable<decimal> reserva { get; set; }

    public virtual analistas analistas { get; set; }
    public virtual auto_reclamo auto_reclamo { get; set; }
    public virtual ICollection<bitacora_autos_unity> bitacora_autos_unity { get; set; }
    public virtual ICollection<bitacora_estados_autos> bitacora_estados_autos { get; set; }
    public virtual ICollection<bitacora_reclamo_auto> bitacora_reclamo_auto { get; set; }
    public virtual cabina cabina { get; set; }
    public virtual ICollection<coberturas_afectadas> coberturas_afectadas { get; set; }
    public virtual ICollection<comentarios_reclamos_autos> comentarios_reclamos_autos { get; set; }
    public virtual ICollection<contacto_auto> contacto_auto { get; set; }
    public virtual ICollection<detalle_pagos_reclamos_autos> detalle_pagos_reclamos_autos { get; set; }
    public virtual estado estado { get; set; }
    public virtual gestores gestores { get; set; }
    public virtual motivos_cierre motivos_cierre { get; set; }
    public virtual usuario usuario { get; set; }
    public virtual talleres talleres { get; set; }
}

public partial class reclamos_medicos
{
    public reclamos_medicos()
    {
        this.bitacora_reclamos_medicos = new HashSet<bitacora_reclamos_medicos>();
        this.comentarios_reclamos_medicos = new HashSet<comentarios_reclamos_medicos>();
        this.detalle_gasto_medico = new HashSet<detalle_gasto_medico>();
        this.detalle_pagos_reclamos_medicos = new HashSet<detalle_pagos_reclamos_medicos>();
        this.ingreso_cheques = new HashSet<ingreso_cheques>();
        this.recibos_medicos = new HashSet<recibos_medicos>();
    }

    public long id { get; set; }
    public string asegurado { get; set; }
    public string titular { get; set; }
    public string telefono { get; set; }
    public string correo { get; set; }
    public string empresa { get; set; }
    public string metodo { get; set; }
    public int id_estado { get; set; }
    public int id_usuario { get; set; }
    public int id_cabina { get; set; }
    public long id_reg_reclamos_medicos { get; set; }
    public Nullable<short> codigo_pais { get; set; }
    public Nullable<System.TimeSpan> hora_cierre { get; set; }
    public string tipo_reclamo { get; set; }
    public string usuario_unity { get; set; }
    public string estado_unity { get; set; }
    public Nullable<System.DateTime> fecha_completa_commit { get; set; }
    public Nullable<System.TimeSpan> hora_commit { get; set; }
    public Nullable<System.DateTime> fecha_commit { get; set; }
    public Nullable<System.DateTime> fecha_asignacion { get; set; }
    public Nullable<System.DateTime> fecha_apertura { get; set; }
    public Nullable<System.DateTime> fecha_envio_aseg { get; set; }
    public Nullable<System.DateTime> fecha_espera_asegurado { get; set; }
    public Nullable<System.DateTime> fecha_envio_notificacion { get; set; }
    public Nullable<System.DateTime> fecha_recepcion_cheque { get; set; }
    public Nullable<System.DateTime> fecha_envio_cheque { get; set; }
    public Nullable<System.DateTime> fecha_cierre { get; set; }
    public Nullable<System.DateTime> fecha_revision { get; set; }
    public Nullable<System.DateTime> fecha_gasto { get; set; }
    public Nullable<System.DateTime> fecha_modificacion { get; set; }
    public Nullable<System.DateTime> fecha_visualizar { get; set; }
    public string num_reclamo { get; set; }
    public string observacion { get; set; }
    public string recepcion { get; set; }
    public string detalle_cliente { get; set; }
    public string observaciones { get; set; }
    public Nullable<bool> bandera_asegurado { get; set; }
    public Nullable<bool> bandera_aseguradora { get; set; }
    public Nullable<bool> bandera_cheque { get; set; }
    public Nullable<bool> bandera_cierre { get; set; }
    public string destino { get; set; }
    public Nullable<bool> acs { get; set; }
    public string detalle_no_conforme { get; set; }
    public Nullable<bool> no_conforme { get; set; }
    public Nullable<System.DateTime> fecha_no_conforme { get; set; }
    public Nullable<System.DateTime> fecha_cierre_no_conforme { get; set; }
    public string observacion_no_conforme { get; set; }
    public string documento { get; set; }
    public string direccion { get; set; }

    public virtual ICollection<bitacora_reclamos_medicos> bitacora_reclamos_medicos { get; set; }
    public virtual cabina cabina { get; set; }
    public virtual ICollection<comentarios_reclamos_medicos> comentarios_reclamos_medicos { get; set; }
    public virtual ICollection<detalle_gasto_medico> detalle_gasto_medico { get; set; }
    public virtual ICollection<detalle_pagos_reclamos_medicos> detalle_pagos_reclamos_medicos { get; set; }
    public virtual estado estado { get; set; }
    public virtual ICollection<ingreso_cheques> ingreso_cheques { get; set; }
    public virtual ICollection<recibos_medicos> recibos_medicos { get; set; }
    public virtual reg_reclamos_medicos reg_reclamos_medicos { get; set; }
    public virtual usuario usuario { get; set; }
}

public partial class reclamos_varios
{
    public reclamos_varios()
    {
        this.bitacora_estados_reclamos_varios = new HashSet<bitacora_estados_reclamos_varios>();
        this.bitacora_reclamos_varios = new HashSet<bitacora_reclamos_varios>();
        this.coberturas_afectadas_danios = new HashSet<coberturas_afectadas_danios>();
        this.comentarios_reclamos_varios = new HashSet<comentarios_reclamos_varios>();
        this.detalle_pagos_reclamos_varios = new HashSet<detalle_pagos_reclamos_varios>();
    }

    public int id { get; set; }
    public string boleta { get; set; }
    public string titular { get; set; }
    public string ubicacion { get; set; }
    public string tipo_servicio { get; set; }
    public Nullable<System.TimeSpan> hora { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string reportante { get; set; }
    public string telefono { get; set; }
    public string ajustador { get; set; }
    public string version { get; set; }
    public string metodo { get; set; }
    public int id_estado { get; set; }
    public int id_usuario { get; set; }
    public int id_reg_reclamos_varios { get; set; }
    public int id_cabina { get; set; }
    public Nullable<short> codigo_pais { get; set; }
    public System.TimeSpan hora_commit { get; set; }
    public System.DateTime fecha_commit { get; set; }
    public string estado_unity { get; set; }
    public string usuario_unity { get; set; }
    public Nullable<System.DateTime> fecha_cierre { get; set; }
    public Nullable<System.TimeSpan> hora_cierre { get; set; }
    public string num_reclamo { get; set; }
    public string num_contrato { get; set; }
    public Nullable<short> id_gestor { get; set; }
    public Nullable<int> id_analista { get; set; }
    public Nullable<int> id_taller { get; set; }
    public string observaciones { get; set; }
    public string estado_reclamo_unity { get; set; }
    public Nullable<bool> prioritario { get; set; }
    public Nullable<bool> complicado { get; set; }
    public Nullable<bool> cuello_botella { get; set; }
    public Nullable<bool> compromiso_pago { get; set; }
    public string asignado_por { get; set; }
    public Nullable<System.DateTime> fecha_asignacion { get; set; }
    public Nullable<System.DateTime> fecha_visualizar { get; set; }
    public Nullable<System.DateTime> fecha_apertura_reclamo { get; set; }
    public Nullable<System.DateTime> fecha_cierre_reclamo { get; set; }
    public string motivo_cierre { get; set; }
    public Nullable<bool> acs { get; set; }
    public Nullable<int> id_no_conforme { get; set; }
    public string detalle_no_conforme { get; set; }
    public Nullable<bool> no_conforme { get; set; }
    public Nullable<System.DateTime> fecha_no_conforme { get; set; }
    public Nullable<System.DateTime> fecha_cierre_no_conforme { get; set; }
    public string observacion_no_conforme { get; set; }
    public Nullable<bool> b_carta_cierre_interno { get; set; }
    public Nullable<bool> b_carta_declinado { get; set; }
    public Nullable<bool> b_carta_envio_cheque { get; set; }
    public Nullable<bool> b_carta_deducible_anual { get; set; }
    public Nullable<bool> b_carta_cierre_reclamo { get; set; }
    public Nullable<bool> b_carta_alerta_tiempo { get; set; }
    public Nullable<decimal> reserva { get; set; }
    public string documentos { get; set; }
    public Nullable<bool> problema_ajustador { get; set; }
    public Nullable<bool> problema_taller { get; set; }
    public Nullable<bool> problema_cabina { get; set; }
    public Nullable<bool> problema_ejecutivo { get; set; }
    public Nullable<bool> problema_aseguradora { get; set; }
    public string comentario_ajustador { get; set; }
    public string comentario_taller { get; set; }
    public string comentario_cabina { get; set; }
    public string comentario_ejecutivo { get; set; }
    public string comentario_aseguradora { get; set; }
    public Nullable<System.DateTime> fecha_problema { get; set; }
    public Nullable<bool> reaseguro { get; set; }
    public Nullable<decimal> reserva_final { get; set; }
    public Nullable<decimal> deducible_reserva { get; set; }

    public virtual analistas analistas { get; set; }
    public virtual ICollection<bitacora_estados_reclamos_varios> bitacora_estados_reclamos_varios { get; set; }
    public virtual ICollection<bitacora_reclamos_varios> bitacora_reclamos_varios { get; set; }
    public virtual cabina cabina { get; set; }
    public virtual ICollection<coberturas_afectadas_danios> coberturas_afectadas_danios { get; set; }
    public virtual ICollection<comentarios_reclamos_varios> comentarios_reclamos_varios { get; set; }
    public virtual ICollection<detalle_pagos_reclamos_varios> detalle_pagos_reclamos_varios { get; set; }
    public virtual estado estado { get; set; }
    public virtual gestores gestores { get; set; }
    public virtual reg_reclamo_varios reg_reclamo_varios { get; set; }
    public virtual usuario usuario { get; set; }
    public virtual talleres talleres { get; set; }
}

public partial class reg_reclamo_varios
{
    public reg_reclamo_varios()
    {
        this.reclamos_varios = new HashSet<reclamos_varios>();
    }

    public int id { get; set; }
    public string poliza { get; set; }
    public string asegurado { get; set; }
    public Nullable<int> cliente { get; set; }
    public string status { get; set; }
    public string tipo { get; set; }
    public string direccion { get; set; }
    public string ramo { get; set; }
    public string ejecutivo { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public string estado_poliza { get; set; }
    public string vip { get; set; }
    public Nullable<decimal> suma_asegurada { get; set; }
    public string moneda { get; set; }
    public Nullable<short> num_ramo { get; set; }
    public Nullable<short> gestor { get; set; }
    public Nullable<short> cia { get; set; }
    public Nullable<short> secren { get; set; }
    public string vendedor { get; set; }
    public string contacto { get; set; }
    public string correo_contacto { get; set; }
    public string telefono_contacto { get; set; }

    public virtual ICollection<reclamos_varios> reclamos_varios { get; set; }
}

public partial class reg_reclamos_medicos
{
    public reg_reclamos_medicos()
    {
        this.autorizaciones = new HashSet<autorizaciones>();
        this.reclamos_medicos = new HashSet<reclamos_medicos>();
    }

    public long id { get; set; }
    public string asegurado { get; set; }
    public string poliza { get; set; }
    public string ramo { get; set; }
    public string tipo { get; set; }
    public string clase { get; set; }
    public string ejecutivo { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public string estado_poliza { get; set; }
    public string vip { get; set; }
    public string moneda { get; set; }
    public string certificado { get; set; }
    public Nullable<short> secren { get; set; }
    public string tipo_registro { get; set; }
    public Nullable<int> cliente { get; set; }
    public string telefono_acs { get; set; }

    public virtual ICollection<autorizaciones> autorizaciones { get; set; }
    public virtual ICollection<reclamos_medicos> reclamos_medicos { get; set; }
}

public partial class registros_consultas
{
    public int id { get; set; }
    public string asegurado { get; set; }
    public string sucursal { get; set; }
    public string codigo { get; set; }
    public string servicio { get; set; }
    public string placa { get; set; }
    public string poliza { get; set; }
    public string chasis { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
}

public partial class registros_vifrio
{
    public int id { get; set; }
    public string asegurado { get; set; }
    public string sucursal { get; set; }
    public string codigo { get; set; }
    public string servicio { get; set; }
    public string placa { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
}

public partial class sucursal
{
    public sucursal()
    {
        this.cabina = new HashSet<cabina>();
    }

    public int id { get; set; }
    public string nombre { get; set; }
    public int id_empresa { get; set; }

    public virtual ICollection<cabina> cabina { get; set; }
    public virtual empresa empresa { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class talleres
{
    public talleres()
    {
        this.reclamo_auto = new HashSet<reclamo_auto>();
        this.reclamos_varios = new HashSet<reclamos_varios>();
    }

    public int id { get; set; }
    public string nombre { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public string correo { get; set; }
    public Nullable<bool> estado { get; set; }

    public virtual ICollection<reclamo_auto> reclamo_auto { get; set; }
    public virtual ICollection<reclamos_varios> reclamos_varios { get; set; }
}

public partial class tipo_documentos
{
    public tipo_documentos()
    {
        this.documentos_solicitados = new HashSet<documentos_solicitados>();
    }

    public int id { get; set; }
    public string descripcion { get; set; }
    public string tipo { get; set; }
    public string usuario { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<bool> estado { get; set; }

    public virtual ICollection<documentos_solicitados> documentos_solicitados { get; set; }
}

public partial class tipo_reclamos
{
    public tipo_reclamos()
    {
        this.actividades = new HashSet<actividades>();
    }

    public int id { get; set; }
    public string nombre { get; set; }

    public virtual ICollection<actividades> actividades { get; set; }
}

public partial class usuario
{
    public usuario()
    {
        this.autorizaciones = new HashSet<autorizaciones>();
        this.reclamo_auto = new HashSet<reclamo_auto>();
        this.reclamos_medicos = new HashSet<reclamos_medicos>();
        this.reclamos_varios = new HashSet<reclamos_varios>();
    }

    public int id { get; set; }
    public Nullable<bool> estado { get; set; }
    public Nullable<short> tipo { get; set; }
    public string nombre { get; set; }
    public Nullable<System.Guid> id_usuario { get; set; }
    public int id_cabina { get; set; }
    public string nombre_completo { get; set; }
    public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    public string correo { get; set; }
    public Nullable<short> numero_gestor { get; set; }
    public Nullable<bool> permiso_movil { get; set; }
    public string pais { get; set; }
    public string empresa { get; set; }
    public string sucursal { get; set; }
    public string cabina { get; set; }
    public Nullable<short> codigo { get; set; }
    public string rol { get; set; }
    public string backOffice { get; set; }

    public virtual ICollection<autorizaciones> autorizaciones { get; set; }
    public virtual cabina cabina1 { get; set; }
    public virtual ICollection<reclamo_auto> reclamo_auto { get; set; }
    public virtual ICollection<reclamos_medicos> reclamos_medicos { get; set; }
    public virtual ICollection<reclamos_varios> reclamos_varios { get; set; }
}

public partial class v_producto_no_conforme
{
    public long id { get; set; }
    public Nullable<int> Cliente { get; set; }
    public string Poliza { get; set; }
    public string Asegurado { get; set; }
    public string Aseguradora { get; set; }
    public string ramo { get; set; }
    public Nullable<System.DateTime> Fecha_Creacion { get; set; }
    public Nullable<System.DateTime> Fecha_Cierre { get; set; }
    public string Detalle { get; set; }
    public string Observacion { get; set; }
    public string Tipo { get; set; }
    public string estado { get; set; }
}

public partial class ViewBusquedaAuto
{
    public int id { get; set; }
    public string ramo { get; set; }
    public string poliza { get; set; }
    public Nullable<System.DateTime> vigi { get; set; }
    public Nullable<System.DateTime> vigf { get; set; }
    public string nombre { get; set; }
    public string color { get; set; }
    public string gst_nombre { get; set; }
    public string contratante { get; set; }
    public string motor { get; set; }
    public string chasis { get; set; }
    public string marca { get; set; }
    public string placa { get; set; }
    public string solicitud { get; set; }
    public string secart { get; set; }
    public string modelo { get; set; }
    public string valorauto { get; set; }
    public string propietario { get; set; }
    public string estado { get; set; }
    public Nullable<int> suma_aseg { get; set; }
    public string tipo { get; set; }
    public string asegurado { get; set; }
    public string vip { get; set; }
    public Nullable<int> numero_gestor { get; set; }
    public string inciso { get; set; }
    public string moneda { get; set; }
    public string direccion { get; set; }
    public Nullable<short> cia { get; set; }
    public Nullable<short> secren { get; set; }
    public Nullable<int> cliente { get; set; }
    public string programa { get; set; }
    public Nullable<decimal> prima { get; set; }
    public Nullable<decimal> porcom { get; set; }
    public Nullable<int> vendedor { get; set; }
}

public partial class viewCoberturasAutos
{
    public int id { get; set; }
    public string descr { get; set; }
    public string placa { get; set; }
    public string chasis { get; set; }
    public Nullable<double> limite1 { get; set; }
    public Nullable<double> limite2 { get; set; }
    public Nullable<double> deducible { get; set; }
    public Nullable<double> prima { get; set; }
    public Nullable<double> sumaaseg { get; set; }
}

public partial class vistaBusquedaPolizaMovil
{
    public int id { get; set; }
    public string tipoPol { get; set; }
    public string poliza { get; set; }
    public string NumRamo { get; set; }
    public string ramo { get; set; }
    public Nullable<System.DateTime> vigi { get; set; }
    public Nullable<System.DateTime> vigf { get; set; }
    public string gst_nombre { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public Nullable<int> cliente { get; set; }
    public string status { get; set; }
    public string Asegurado { get; set; }
    public string tipo { get; set; }
    public string direccion { get; set; }
    public Nullable<int> sumaaseg { get; set; }
}

public partial class vistaReclamosDaños
{
    public int id { get; set; }
    public string poliza { get; set; }
    public string ramo { get; set; }
    public Nullable<System.DateTime> vigi { get; set; }
    public Nullable<System.DateTime> vigf { get; set; }
    public string gst_nombre { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public string cliente { get; set; }
    public string status { get; set; }
    public string tipo { get; set; }
    public string direccion { get; set; }
    public string asegurado { get; set; }
    public Nullable<int> suma_aseg { get; set; }
    public string vip { get; set; }
    public Nullable<int> numero_gestor { get; set; }
    public string moneda { get; set; }
    public Nullable<short> num_ramo { get; set; }
    public Nullable<short> gestor { get; set; }
    public Nullable<short> cia { get; set; }
    public Nullable<short> secren { get; set; }
    public Nullable<decimal> prima { get; set; }
    public Nullable<decimal> porcom { get; set; }
    public Nullable<int> vendedor { get; set; }
    public string contacto { get; set; }
    public string correo { get; set; }
    public string telefono_contacto { get; set; }
}

public partial class vistaReclamosMedicos
{
    public int id { get; set; }
    public string ramo { get; set; }
    public string poliza { get; set; }
    public string tipo { get; set; }
    public string clase { get; set; }
    public string asegurado { get; set; }
    public string nombre { get; set; }
    public string gst_nombre { get; set; }
    public string contratante { get; set; }
    public Nullable<System.DateTime> vigi { get; set; }
    public Nullable<System.DateTime> vigf { get; set; }
    public string estado_poliza { get; set; }
    public Nullable<short> maxren { get; set; }
    public string vip { get; set; }
    public Nullable<int> numero_gestor { get; set; }
    public Nullable<short> secren { get; set; }
    public string moneda { get; set; }
    public string certificado { get; set; }
    public Nullable<int> cliente { get; set; }
    public string status { get; set; }
    public Nullable<decimal> prima { get; set; }
    public Nullable<decimal> porcom { get; set; }
    public string fechanac { get; set; }
    public string parentesco { get; set; }
}

public partial class pa_cargar_asegurados_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class pa_cargar_autos_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class pa_cargar_danios_varios_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class pa_eficiencia_autos_Result
{
    public string Usuario { get; set; }
    public Nullable<int> Pendientes { get; set; }
    public Nullable<int> Nuevos { get; set; }
    public Nullable<int> Cerrados { get; set; }
    public Nullable<int> Cerrados_Con_Importacion_Fuera_Tiempo { get; set; }
    public Nullable<int> Cerrados_Sin_Importacion_Fuera_Tiempo { get; set; }
    public Nullable<int> Pendientes_Con_Importacion_Fuera_Tiempo { get; set; }
    public Nullable<int> Pendientes_Sin_Importacion_Fuera_Tiempo { get; set; }
    public Nullable<double> Eficiencia_Cierre { get; set; }
    public Nullable<double> Añejamiento { get; set; }
}

public partial class pa_eficiencia_colectivos_Result
{
    public string Nombre { get; set; }
    public Nullable<int> Pendientes { get; set; }
    public Nullable<int> Nuevos { get; set; }
    public Nullable<int> Cerrados { get; set; }
    public Nullable<int> Fuera_de_tiempo { get; set; }
    public Nullable<int> Ejecucion { get; set; }
}

public partial class pa_eficiencia_danos_varios_Result
{
    public string Usuario { get; set; }
    public Nullable<int> Pendientes { get; set; }
    public Nullable<int> Nuevos { get; set; }
    public Nullable<int> Cerrados { get; set; }
    public Nullable<int> Cerrados_Con_Reaseguro_Fuera_Tiempo { get; set; }
    public Nullable<int> Cerrados_Sin_Reaseguro_Fuera_Tiempo { get; set; }
    public Nullable<int> Pendientes_Con_Reaseguro_Fuera_Tiempo { get; set; }
    public Nullable<int> Pendientes_Sin_Reaseguro_Fuera_Tiempo { get; set; }
    public Nullable<double> Ejecucion_Cierre { get; set; }
    public Nullable<double> Añejamiento { get; set; }
}

public partial class pa_eficiencia_individuales_Result
{
    public string Nombre { get; set; }
    public Nullable<int> Pendientes { get; set; }
    public Nullable<int> Nuevos { get; set; }
    public Nullable<int> Cerrados { get; set; }
    public Nullable<int> Fuera_de_tiempo { get; set; }
    public Nullable<int> Ejecucion { get; set; }
}

public partial class pa_eficiencia_individuales2_Result
{
    public string Nombre { get; set; }
    public Nullable<int> Pendientes { get; set; }
    public Nullable<int> Nuevos { get; set; }
    public Nullable<int> Cerrados { get; set; }
    public Nullable<int> Pendientes_fuera_tiempo_Q { get; set; }
    public Nullable<int> Pendientes_fuera_tiempo__ { get; set; }
    public Nullable<int> Cerrados_fuera_tiempo_Q { get; set; }
    public Nullable<int> Cerrados_fuera_tiempo__ { get; set; }
    public Nullable<int> Ejecucion { get; set; }
    public Nullable<int> Añejamiento { get; set; }
}

public partial class pa_reclamos_autos_Result
{
    public Nullable<int> secuencia { get; set; }
    public Nullable<short> numRamo { get; set; }
    public string poliza { get; set; }
    public Nullable<short> cia { get; set; }
    public Nullable<short> secren { get; set; }
    public Nullable<short> numero_gestor { get; set; }
    public string num_reclamo { get; set; }
    public Nullable<System.DateTime> Column1 { get; set; }
    public Nullable<System.DateTime> Column2 { get; set; }
    public Nullable<System.DateTime> Column3 { get; set; }
    public string telefono { get; set; }
    public string placa { get; set; }
    public string usuario_unity { get; set; }
    public string ubicacion { get; set; }
    public string nombre { get; set; }
    public string version { get; set; }
    public string contacto { get; set; }
}

public partial class pa_reclamos_varios_Result
{
    public Nullable<int> secuencia { get; set; }
    public Nullable<short> num_ramo { get; set; }
    public string poliza { get; set; }
    public Nullable<short> cia { get; set; }
    public Nullable<short> secren { get; set; }
    public Nullable<short> gestor { get; set; }
    public string num_reclamo { get; set; }
    public Nullable<System.DateTime> Column1 { get; set; }
    public Nullable<System.DateTime> Column2 { get; set; }
    public Nullable<System.DateTime> Column3 { get; set; }
    public string usuario_unity { get; set; }
    public string ubicacion { get; set; }
    public string version { get; set; }
    public string nombre { get; set; }
}

public partial class pa_reporte_problemas_autos_Result
{
    public long id { get; set; }
    public string Poliza { get; set; }
    public Nullable<System.DateTime> Fecha_Registro { get; set; }
    public string Asegurado { get; set; }
    public string Numero_Reclamo { get; set; }
    public string Vehiculo { get; set; }
    public string Taller { get; set; }
    public string Comentario_Taller { get; set; }
    public string Ajustador { get; set; }
    public string Comentario_Ajustador { get; set; }
    public string Cabina { get; set; }
    public string Comentario_Cabina { get; set; }
    public string Aseguradora { get; set; }
    public string Comentario_Aseguradora { get; set; }
    public string Ejecutivo { get; set; }
    public string Comentario_Ejecutivo { get; set; }
}

public partial class pa_reporte_problemas_danios_Result
{
    public int id { get; set; }
    public string Poliza { get; set; }
    public Nullable<System.DateTime> Fecha_Registro { get; set; }
    public string Asegurado { get; set; }
    public string Numero_Reclamo { get; set; }
    public string Taller { get; set; }
    public string Comentario_Taller { get; set; }
    public string Ajustador { get; set; }
    public string Comentario_Ajustador { get; set; }
    public string Cabina { get; set; }
    public string Comentario_Cabina { get; set; }
    public string Aseguradora { get; set; }
    public string Comentario_Aseguradora { get; set; }
    public string Ejecutivo { get; set; }
    public string Comentario_Ejecutivo { get; set; }
}

public partial class pa_reportesAutorizaciones_Result
{
    public string reportante { get; set; }
    public long id { get; set; }
    public string tipo_consulta { get; set; }
    public string tipo_estado { get; set; }
    public string correo { get; set; }
    public string telefono { get; set; }
    public string metodo { get; set; }
    public System.TimeSpan hora_commit { get; set; }
    public System.DateTime fecha_commit { get; set; }
    public Nullable<System.DateTime> fecha_cierre { get; set; }
    public Nullable<System.TimeSpan> hora_cierre { get; set; }
    public string tipo_estado1 { get; set; }
    public string total_tiempo { get; set; }
    public Nullable<bool> tramite_directo { get; set; }
    public string asegurado { get; set; }
    public string poliza { get; set; }
    public string ramo { get; set; }
    public string tipo { get; set; }
    public string clase { get; set; }
    public string ejecutivo { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public string cabina { get; set; }
    public string sucursal { get; set; }
    public string empresa { get; set; }
    public string pais { get; set; }
    public string nombre { get; set; }
}

public partial class pa_reportesAutorizacionesAbiertas_Result
{
    public string reportante { get; set; }
    public long id { get; set; }
    public string tipo_consulta { get; set; }
    public string tipo_estado { get; set; }
    public string correo { get; set; }
    public string telefono { get; set; }
    public string metodo { get; set; }
    public System.TimeSpan hora_commit { get; set; }
    public System.DateTime fecha_commit { get; set; }
    public string tipo_estado1 { get; set; }
    public string asegurado { get; set; }
    public string poliza { get; set; }
    public string ramo { get; set; }
    public string tipo { get; set; }
    public string clase { get; set; }
    public string ejecutivo { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public string cabina { get; set; }
    public string sucursal { get; set; }
    public string empresa { get; set; }
    public string pais { get; set; }
    public string nombre { get; set; }
}

public partial class pa_ReportesAutos_Result
{
    public long id { get; set; }
    public string asegurado { get; set; }
    public string poliza { get; set; }
    public string estado_poliza { get; set; }
    public string placa { get; set; }
    public string marca { get; set; }
    public string modelo { get; set; }
    public string color { get; set; }
    public string chasis { get; set; }
    public string motor { get; set; }
    public string propietario { get; set; }
    public string ejecutivo { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public string boleta { get; set; }
    public string titular { get; set; }
    public string ubicacion { get; set; }
    public Nullable<System.TimeSpan> hora { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string reportante { get; set; }
    public string piloto { get; set; }
    public Nullable<short> edad { get; set; }
    public string telefono { get; set; }
    public string ajustador { get; set; }
    public string version { get; set; }
    public string tipo_servicio { get; set; }
    public Nullable<System.TimeSpan> hora_commit { get; set; }
    public Nullable<System.DateTime> fecha_commit { get; set; }
    public Nullable<System.TimeSpan> hora_cierre { get; set; }
    public Nullable<System.DateTime> fecha_cierre { get; set; }
    public string usuario_unity { get; set; }
    public string estado_unity { get; set; }
    public string cabina { get; set; }
    public string sucursal { get; set; }
    public string empresa { get; set; }
    public string pais { get; set; }
    public string usuario { get; set; }
}

public partial class pa_ReportesDaños_Result
{
    public int id { get; set; }
    public string poliza { get; set; }
    public string asegurado { get; set; }
    public string aseguradora { get; set; }
    public string contratante { get; set; }
    public string ejecutivo { get; set; }
    public string ramo { get; set; }
    public string status { get; set; }
    public string tipo { get; set; }
    public string direccion { get; set; }
    public string boleta { get; set; }
    public string titular { get; set; }
    public string reportante { get; set; }
    public string telefono { get; set; }
    public string ajustador { get; set; }
    public string version { get; set; }
    public string ubicacion { get; set; }
    public Nullable<System.TimeSpan> hora { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public System.TimeSpan hora_commit { get; set; }
    public System.DateTime fecha_commit { get; set; }
    public Nullable<System.TimeSpan> hora_cierre { get; set; }
    public Nullable<System.DateTime> fecha_cierre { get; set; }
    public string cabina { get; set; }
    public string sucursal { get; set; }
    public string empresa { get; set; }
    public string pais { get; set; }
    public string usuario { get; set; }
}

public partial class pa_vista_movil_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class promedio_aseguradoras_Result
{
    public Nullable<int> total_reclamos { get; set; }
    public Nullable<int> Total_dias { get; set; }
    public string aseguradora { get; set; }
    public Nullable<int> promedio { get; set; }
}
